### ISSUE TITLE
Import torch error

### ISSUE THREAD

**Issue by MoonWolf9067** [perry0418/pytorch1.0-installation-tx2#1]
Thank you for the compiled file, I installed the file on TX2, but when I imported the torch, the following error occurred. Can you give me some suggestions?
![torch](https://user-images.githubusercontent.com/22995934/54991871-c7b95e80-4fb5-11e9-932e-aeca87182e82.png)

**Comment by MoonWolf9067** [comment]
Thanks, I solved it already.

**Comment by perry0418** [comment]
sudo apt-get install libgflags-dev libgoogle-glog-dev liblmdb-dev libatlas-base-dev liblmdb-dev libblas-dev libatlas-base-dev libprotobuf-dev libleveldb-dev libsnappy-dev libhdf5-serial-dev protobuf-compiler
